services:
  web:
    image: maven:3.9.2-eclipse-temurin-17-focal
    command: mvn spring-boot:run
    working_dir: /app
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - mysql
  mysql:
    hostname: mysqlserver
    image: mysql:8.0.33
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: meudb
